### PR TITLE
Fix up nginx.conf so that both POS and WIFI is working

### PR DESCRIPTION
**Pull request by nolim1t**
Currently /wifi endpoint isnt working.  Thats because of the last location / redirect which possibly messes it up.

### CODE REVIEW

**Comment by AnotherDroog** [comment]
I thought this was fine already?

**Comment by AnotherDroog** [comment]
This is what I've got in mine,

```
server {
    listen 80 default_server;
    listen [::]:80 default_server;


    location = / {
        root /www/pos;
        try_files $uri $uri/index.html =404;
    }

    location = /wifi {
            root /www;
            auth_basic "Hello Thailand";
            auth_basic_user_file /etc/nginx/.htpasswd;
            try_files $uri $uri/index.html =404;
    }

    location  /api {
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        proxy_pass http://localhost:8088;
    }

    location / {
        proxy_pass http://localhost:8080;
    }
}
```

**Comment by nolim1t** [comment]
the last part needs to be replaced because wifi manager doesn't seem to work

**Comment by AnotherDroog** [comment]
I've tested the above changes work.

Can you test and confirm?

**Comment by AnotherDroog** [comment]
I think we still need one more change,

When the box initially gets setup, it is best to have wifi manager on the http://box.local/ endpoint

**Comment by nolim1t** [comment]
reverted the changes and they seem to be working when we explicitly define the iotwifi endpoints.

We can also put this in 0.5

**Comment by AnotherDroog** [comment]
Testing build...

**Comment by AnotherDroog** [comment]
This is fine now that the missing html file is back.

**Pull request merged**
