### PR TITLE
Release testing: v0.5

### PR DESCRIPTION
**Pull request by AnotherDroog**
I've merged a number of branches into this one to make QA easier.

Let's test what will become v0.5.0

(LNCM-Box-v0.5 ~137MB zip)

Every commit is now automatically built and uploaded as a [draft release](https://github.com/lncm/pi-factory/releases) (you must be a member of LNCM to view it)

Known issues:
* [x] http://box.local/wifi not accessible #193 
* [x] bitcoin.conf missing in `archive`
* [x] swap temporarily disabled (routine needs to block further script execution)
* [x] Let fastsync finish before starting `bitcoind`
* [x] Do not re-download utxo-set / continue instead
* [ ] Change default iotwifi password and document (currently "testing" & "testing")
* [x] Swap missing (see @nolim1t review notes)
* [x] Issues from master to be corrected (Refer to https://github.com/lncm/pi-factory/pull/212)
* [x] Build errors (docker-compose, cffi, gcc, etc)

### CODE REVIEW

**Comment by nolim1t** [comment]
seems to be going in a loop when installing python saying "no space left of this device"

**Comment by AnotherDroog** [comment]
https://we.tl/t-kP5rtcwZcN

**Comment by AnotherDroog** [comment]
Added the missing html file to make WiFi Manager work

**Comment by AnotherDroog** [comment]
Fixed fastsync permissions in latest `noma` commit

**Comment by AnotherDroog** [comment]
This build corresponds to commit b3540d3  

https://we.tl/t-tQX2gDaqpU

**Comment by nolim1t** [comment]
At the branch tip as of now b3540d391ba721f23fa10d1385a1dfe760808c95 , Swap doesn't appear to be created.

```
box:/home/lncm# free -m
             total       used       free     shared    buffers     cached
Mem:           939        822        117          0         24        569
-/+ buffers/cache:        228        710
Swap:            0          0          0
```

**Comment by nolim1t** [comment]
on master 909ae358aa697baf13c789c1d61ebf92f0b031e0

```
box:/home/lncm# free -m
             total       used       free     shared    buffers     cached
Mem:           939        907         32          0         14        765
-/+ buffers/cache:        127        811
Swap:         1023          0       1023
```

**Comment by AnotherDroog** [comment]
Now with logging!
```
/var/log/box-install.log
/var/log/box-postinstall.log
/var/log/noma.log
```

https://github.com/lncm/pi-factory/releases/download/untagged-2cd0cb3dcf29fb332107/lncm-box-v0.5.0.img.zip

**Comment by nolim1t** [comment]
Also.. not sure why its doing this

```
:# ./make_img.sh 
Found Alpine-based system, installing dependencies
OK: 159 MiB in 62 packages
Building lncm-box-v0.5.0.img
Using alpine-rpi-3.9.4-armhf.tar.gz as base distribution
Check for existing wpa_supplicant.automatic.conf
Check for authorized_keys.automatic
Generate fresh box.apkovl.tar.gz from source
Checking for wifi manager
Create and mount 256MB image
256+0 records in
256+0 records out
Create 256MB FAT32 partition and filesystem
mkfs.vfat: can't open '/dev/loop0p1': No such file or directory
Mount FAT partition
mount: mounting /dev/loop0p1 on /mnt/lncm failed: Invalid argument
Extract alpine distribution
```

**Comment by nolim1t** [comment]
Add also #217 to this too.

Should we also get a quick patch for invoicer 0.4 to this?

**Comment by nolim1t** [comment]
I've created #218 so we can start work on getting the latest invoicer into this

**Comment by nolim1t** [comment]
seems the latest build of 0.5 doesn't work completely.

**Comment by nolim1t** [comment]
The box loses connectivity after it has been installed

**Comment by AnotherDroog** [comment]
Yes, it appears to lose WiFi details 

Apkovl is probably not restored or committed correctly

**Comment by nolim1t** [comment]
Few other things we need to add in

* [ ] Fix up this branch so that anyone with the valid hardware is able to contribute
* [ ] Upgrade to invoicer 0.4.0 ( equal to master ). It should also configure itself. (Use [this script](https://github.com/lncm/pi-factory/blob/master/usr/local/sbin/lncm-configinvoicer.py) which requires the [toml](https://github.com/lncm/pi-factory/blob/3d7323a3a95b65ac500419b519c15e6b3862157f/etc/init.d/lncm-post#L49) library, and maybe use [this function to fetch an invoicer config](https://github.com/lncm/pi-factory/blob/3d7323a3a95b65ac500419b519c15e6b3862157f/etc/init.d/lncm-post#L230) ) 
* [ ] Not sure if this is addressed here but the config writing scripts was broken which I fixed up on master

**Comment by nolim1t** [comment]
this is almost 4 months of commits behind master with many stuff still on the todo list. I think should probably just try to cherry pick what we need and put it in a new branch?

Thoughts @AnotherDroog ?

**Comment by nolim1t** [comment]
This has been superseded by a new [v0.5.0 build](https://github.com/lncm/pi-factory/releases/tag/v0.5.0) which will be just system only going forward

**Pull request closed without merging**
