### PR TITLE
Update LND to v0.7.0 on docker-compose

### PR DESCRIPTION
**Pull request by nolim1t**
Currently in testing

### CODE REVIEW

**Comment by nolim1t** [comment]
Seems to be working. I've changed it to v0.7.0-linux-arm

**Comment by nolim1t** [comment]
I've updated docker-compose to use **lncm/lnd:v0.7.0** instead of arch specific.

**Comment by nolim1t** [comment]
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 950,
         "digest": "sha256:6b1c68ef1540a6d1fdeb75a48c192d6a3905f63920513b3715e474f74e630d9d",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 950,
         "digest": "sha256:f55c26d0ffac307d569c055588268e27898d877a152f8f295feaa76004a94d16",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      }
   ]
}
```

**Comment by nolim1t** [comment]
I've tested this on Mac and Linux and ARM and this now works

**Comment by meeDamian** [comment]
There's a full release process in place for lnd.  Why are you doing it manually? Is it not explained properly?  What's the obstacle exactly, please advice.

**Comment by meeDamian** [comment]
Also, if you do need to do it by hand, please at least stick to the same naming convention as was used before.

**Comment by nolim1t** [comment]
@meeDamian 

> There's a full release process in place for lnd. Why are you doing it manually? Is it not explained properly? What's the obstacle exactly, please advice.

the reason why I build 0.7.0 manually was I wanted watchtower client and server support, and neutrino for light clients

**Comment by nolim1t** [comment]
> Also, if you do need to do it by hand, please at least stick to the same naming convention as was used before.

noted.. suggestions?

**Comment by meeDamian** [comment]
> @meeDamian
> 
> > There's a full release process in place for lnd. Why are you doing it manually? Is it not explained properly? What's the obstacle exactly, please advice.
> 
> the reason why I build 0.7.0 manually was I wanted watchtower client and server support, and neutrino for light clients

Is it not included in the official release?

**Comment by meeDamian** [comment]
> > Also, if you do need to do it by hand, please at least stick to the same naming convention as was used before.
> 
> noted.. suggestions?

Just stick to the same versioning format that was used so far (see on Docker Hub).  Alternatively if it is a different version (with some extra flags), perhaps mark it with something more obvious, ex: `lnd:extended-0.7.0`?

**Comment by nolim1t** [comment]
> Is it not included in the official release?

Nope you have to switch it on or ```lncli tower info``` is not showing. Also neutrino mode doesn't start in mainnet without turning off the switches

> Just stick to the same versioning format that was used so far (see on Docker Hub). Alternatively if it is a different version (with some extra flags), perhaps mark it with something more obvious, ex: `lnd:extended-0.7.0`?

Maybe the commit hash?

**Comment by AnotherDroog** [comment]
For what it's worth, I've confirmed it working

**Comment by nolim1t** [comment]
because you're using the one I built which is in pi-factory master. On LND mainline, neutrino does not start because of [this](https://github.com/lightningnetwork/lnd/blob/7767eecbb8ecfe233ad5c712630fa12474f00441/config.go#L817) on mainnet. pi-factory master uses a docker image which is based off [this fork](https://gitlab.com/nolim1t/lnd/tree/v0.7.0-beta-mainnet)


I'll build 0.7.1 soon with the new naming format.

**Comment by meeDamian** [comment]
Since CI-enforced naming for `lnd` is:

| version | type     | |
|---------|----------|-|
| `X.X`   | manifest | for latest minor version of `lnd`
| `X.X.X` | manifest | for specific `lnd` version
| `X.X.X-linux-armv6`<br>`0.x.x-linux-armv7`<br>`0.x.x-linux-amd64` | image | for a specific version/architecture combo of `lnd`

Can images that introduce extra feature be tagged with a suffix that describes it? example:

`0.x-neutrino`, `0.x.x-neutrino`, `0.x.x-linux-<arch>-neutrino`?


Optionally, what I personally like, we'd also add a suffix indicating it was a manual build (not CI).

Example: `-neutrino-manual-build`, or `-neutrino-not-ci`


Opinions @nolim1t @AnotherDroog ?

**Comment by meeDamian** [comment]
Just [triggered _the vanilla_ `0.7.1-beta` build](https://travis-ci.com/lncm/docker-lnd/builds/121961116) via [this commit](https://github.com/lncm/docker-lnd/commit/8e7d580a84ecd19ecb1f2490d64100248ce19db5).

**Comment by nolim1t** [comment]
I've started using the new scheme from 0.7.1 onwards.

**Pull request merged**
