### PR TITLE
Add LICENSE file and update scripts to apache license

### PR DESCRIPTION
**Pull request by nolim1t**
Add license file to project.

### CODE REVIEW

**Comment by AnotherDroog** [comment]
We might also want to change the license of the build script to match Apache, just for simplicity

**Comment by nolim1t** [comment]
Updated.

**Comment by nolim1t** [comment]
License is consistant to whats in the build script (MIT license)

**Comment by AnotherDroog** [comment]
I meant, let's change the build script to also use Apache

**Comment by nolim1t** [comment]
Ok sounds good

**Comment by nolim1t** [comment]
Now using Apache 2.0 license with the scripts

**Comment by AnotherDroog** [comment]
Thanks for that

**Pull request merged**
