### PR TITLE
[TO TEST] [To: 3.9.0] Add new invoicer config

### PR DESCRIPTION
**Pull request by nolim1t**
Add invoicer config based on docker-compose settings in preparation for https://github.com/lncm/invoicer/commit/4bead5b0a4a59ad90f39e8cd9ff71cf6c6706fdd

## TODO

* Update rewrite script 
* Copy to /media/important

### CODE REVIEW

**Comment by nolim1t** [comment]
@meeDamian 

> template strings
So what do you want to use for the password? We don't know what the password is going to be.

> Paths should probably be `/media/*`
Yes but this exists inside the container, and the pathname we are using is **/lnd** .. lets not change this too sudden

> Let's not put default passwords here.
removed.

> Default fields can be omitted.
specify which ones.

**Comment by meeDamian** [comment]
The default paths the `invoicer` expects in the container are in `/root/.invoicer/*`.

Instead of template strings we should be using proper config syntax parsing.

**Comment by nolim1t** [comment]
Please explain how you would like to handle inserting in the username and password that was generated in the setup.

Also ~/.invoicer makes no sense for tls and macaroons  as these files are lnd files.

**Comment by meeDamian** [comment]
1. Read config with something that understands TOML,
2. add users to appropriate section
3. Save file.


We can probably docker-compose volume mount files in there's appropriate locations.

**Comment by nolim1t** [comment]
how do I do it in BASH

**Comment by meeDamian** [comment]
We shouldn't do it in shell.

**Comment by meeDamian** [comment]
I'll write more later

**Comment by nolim1t** [comment]
Why not it does the job in 1-2 lines

**Comment by meeDamian** [comment]
Because it's prone to errors.
Because it's not very  flexible (ex. easy to add first rpc user to bitcoind, but what if we need more later? What if we need to change password, or remove user?).
Because we end up with 2 config files, one that's an invalid template, and one that's post changes. 
Because it's non standard and will need documentation. 
Because its behavior will be a mystery to anyone reading our code.

Note: I'm NOT saying we need to change it right now. I'm saying that's the best path for us to go.

**Comment by nolim1t** [comment]
Agree that shell is not the best, but for a short term MVP it meets our needs

**Comment by AnotherDroog** [comment]
What is the status on this @meeDamian @nolim1t ?

**Comment by nolim1t** [comment]
I'd say put it in now, and add the re-write code into the setup scripts.

Then iterate on re-writing it into python (or whatever) later.

**Pull request merged**
