### PR TITLE
Stop more gracefully patch to management script

### PR DESCRIPTION
**Pull request by nolim1t**
Because theres a directive in the docker-compose to automatically restart some services, have added some more stuff to help it stop nicely.

### CODE REVIEW

**Comment by AnotherDroog** [comment]
There needs to be a check if bitcoind is shutdown before stopping the container, otherwise databases can become inconsistent. Rebuilding them takes a long time!

**Comment by nolim1t** [comment]
Will put this on the backburner for now

**Comment by nolim1t** [comment]
# Stop BTC more gracefully first command

```
docker exec -it btcbox bitcoin-cli -datadir=/home/bitcoin/.bitcoin stop
```

# Check if BTC is running

```
docker ps | grep -c btcbox
```

if 0 then stop the container completely

**Comment by AnotherDroog** [comment]
If `1` it's best to continue waiting with shutdown, or attempt to `bitcoin-cli stop` again

If `0` compose_btcbox_1 is stopped already and all is well

**Comment by nolim1t** [comment]
This is working quite well on my alpine box for restarting, so I'm gonna copy it to the food4thought box @AnotherDroog

**Comment by AnotherDroog** [comment]
This looks very good, definitely makes shutdowns safer!

**Pull request merged**
