### PR TITLE
[DO NOT MERGE!] Automated image creation

### PR DESCRIPTION
**Pull request by meeDamian**
I've changed a few things there:

1. default files (wifi creds, ssh keys, etc) are now expected to be in `defaults/` - it makes Docker `COPY` much easier…
1. Same with downloads, all downloaded files are now expected in `downloads/`
1. I'm initially focusing on `Alpine` only; Debian-based OS support can be added to the script later.
1. I think it makes the most sense to have one, well-commented and clear script go through the entire setup
1. While it might be convenient for us to have all vars declared on top, I think our focus should be on the less technical people reading our script, and to make it as easy to read for them as possible, we should define vars as close to where they're being used as possible (IMO)
1. I'm trying to both add decent comments, as well as good logging on what's happening while the script is running
1. I think the script shouldn't try to handle multiple versions of Alpine, etc. We should probably hard-code all exact versions in the file - we'll still have all previous versions in the git history. Hardcoding versions removes the ambiguity of how was the script run.

 NOTE: this thing is still very much a Work-In-Progress, so please **DO NOT MERGE**.

### CODE REVIEW

**Comment by AnotherDroog** [comment]
> I've changed a few things there:
> 
> 1. default files (wifi creds, ssh keys, etc) are now expected to be in `defaults/` - it makes Docker `COPY` much easier…
That makes sense, at the cost of making the build script a little more complex.
> 2. Same with downloads, all downloaded files are now expected in `downloads/`
Good thinking to separate *input* and *output* files
> 3. I'm initially focusing on `Alpine` only; Debian-based OS support can be added to the script later.
Sure
> 4. I think it makes the most sense to have one, well-commented and clear script go through the entire setup
This is on my to-do list
> 5. While it might be convenient for us to have all vars declared on top, I think our focus should be on the less technical people reading our script, and to make it as easy to read for them as possible, we should define vars as close to where they're being used as possible (IMO)
I agree about defining vars close. Constants can stay at the top.
> 6. I'm trying to both add decent comments, as well as good logging on what's happening while the script is running
Thanks, when I combine these scripts I'll do some refactoring
> 7. I think the script shouldn't try to handle multiple versions of Alpine, etc. We should probably hard-code all exact versions in the file - we'll still have all previous versions in the git history. Hardcoding versions removes the ambiguity of how was the script run.
Build script should continue to work, the process is very straightforward. What tends to break is internal to Alpine. I'd like to discuss solutions further if you think we can improve here.
> NOTE: this thing is still very much a Work-In-Progress, so please **DO NOT MERGE**.

**Comment by NoahO** [comment]
Re: locking versions, can we make it a variable somehow, so that we can have automated testing of eg newer versions of alpine? I don’t mean automated releases, but it would be good if we know early when changes in alpine break our project, not just later on when we are trying to upgrade the alpine version, but right away.

**Comment by AnotherDroog** [comment]
> Re: locking versions, can we make it a variable somehow, so that we can have automated testing of eg newer versions of alpine? We’ve had that from early on in our image building scripts. 

Unfortunately, due to outdated WiFi chipset firmware and the fact that kernel modules are being signed in recent releases, changing that alpine version constant will only confirm that the radio is currently not working at all on 3B+ with stock alpine. 

The fixed version is going to be released by alpine this month. Of course I’ll immediately open a PR to bump the version in our scripts and let us test it!

**Comment by nolim1t** [comment]
We're using github-actions now to build an image each time, and to upload them to a release when tagged.

**Pull request closed without merging**
