### PR TITLE
Update README to make it more consistent

### PR DESCRIPTION
**Pull request by nolim1t**
Update README to make the tarball file more consistent with the build version

### CODE REVIEW

**Comment by AnotherDroog** [comment]
Thank you for the effort.

This change isn't quite right since box.apkovl.tar.gz is _inside_ the lncm-box.tar.gz

It makes more sense to explain to people that they can unpack the lncm-box.tar.gz and then modify box.apkovl.tar.gz or modify box.apkovl.tar.gz from the SD card

**Comment by nolim1t** [comment]
OK I up made the requested changes to be more clear whats inside lncm-box

**Comment by nolim1t** [comment]
so @AnotherDroog I updated the README (fixed up the numbering as well), and also added the step which includes your patch for Raspberry PI 3b+

**Comment by AnotherDroog** [comment]
Sorry, now the link is garbled, needs some fixes

**Comment by AnotherDroog** [comment]
Also it needs to mention that modloop.zip must be extracted to replace the one in /boot

**Comment by nolim1t** [comment]
what do you mean by the link is garbled?

It seems to work when you [click on it](https://github.com/nolim1t/pi-factory/tree/master/variant-alpine)

**Comment by nolim1t** [comment]
@AnotherDroog  This was already added

```
If you have a Raspberry PI 3b+ then fetch this patch if you installed 3.8.1 or lower and put it in /boot. tar.gz
```

**Comment by AnotherDroog** [comment]
In your sentence the link points to tar.gz when in fact it's .zip

**Comment by nolim1t** [comment]
Ok good catch @AnotherDroog .. I copy and pasted the link lol.

Fixed now

**Comment by AnotherDroog** [comment]
Thanks

**Pull request merged**
