### PR TITLE
Update to Alpine 3.9.4

### LINKED ISSUE #79: Reduce memory assigned to GPU
Edit config.txt on FAT partition

### LINKED ISSUE #140: Update Alpine to the latest and investigate use of postmarketOS for orchestration
Also verify if `make_modloop.sh` is no longer necessary, and if that's the case, remove it.

### PR DESCRIPTION
**Pull request by AnotherDroog**
close #140 

- Fixes wifi firmware
- Remove modloop workaround
- Add config.txt
- Reduce gpu_mem; close #79

### CODE REVIEW

**Comment by AnotherDroog** [comment]
Corresponding image:

https://github.com/lncm/pi-factory/releases/download/untagged-ff0eb139d58f4b58a5db/lncm-box-v0.5.0.img.zip

**Comment by AnotherDroog** [comment]
gpu_mem might have to be 32

**Comment by nolim1t** [comment]
Cool will test this

**Comment by nolim1t** [comment]
These are the errors Im getting when running ```./make_img.sh``` on alpine

```
Mount FAT partition
Extract alpine distribution
Extract iotwifi container
Extract nginx container
Extract cache dir for docker and avahi
tar (child): cache-3.9.4.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Copy latest box.apkovl tarball
Copy boot options in config.txt
Flush writes to disk
Unmount
Compress img as zip
./make_img.sh: line 166: zip: not found
```

The zip not found is irrelevant I think, but not sure about ```tar (child): cache-3.9.4.tar.gz: Cannot open: No such file or directory```

**Comment by AnotherDroog** [comment]
> The zip not found is irrelevant I think, but not sure about `tar (child): cache-3.9.4.tar.gz: Cannot open: No such file or directory`

You can generate cache-3.9.4.tar.gz using make_cache.sh script on an alpine system (set --arch armhf if not on ARM)

**Comment by AnotherDroog** [comment]
I'll merge this now since @noaho confirmed it works

**Pull request merged**
